import "./globals.css";
import Header from "@/components/(global)/Header";
import Menu from "@/components/(global)/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          rel="stylesheet"
        ></link>
        <title>Document</title>
      </head>
      <body>
        <Header></Header>
        {children}
        <Menu></Menu>
      </body>
    </html>
  );
}
